version: "3"

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build: .
    command: uv run fastapi dev --port 8000 --host 0.0.0.0
    ports:
      - "8000:8000"